// Generated by CoffeeScript 2.6.1
//###########################################################
export var postData = async function(url, data) {
  var err, options, response;
  options = {
    method: 'POST',
    credentials: 'omit',
    body: JSON.stringify(data),
    headers: {
      'Content-Type': 'application/json'
    }
  };
  try {
    response = (await fetch(url, options));
    if (!response.ok) {
      throw new Error("Response not ok - status: " + response.status + "!");
    }
    return response.json();
  } catch (error) {
    err = error;
    throw new Error("Network Error: " + err.message);
  }
};

//###########################################################
export var getData = async function(url) {
  var err, response;
  try {
    response = (await fetch(url));
    if (!response.ok) {
      throw new Error("Response not ok - status: " + response.status + "!");
    }
    return response.json();
  } catch (error) {
    err = error;
    throw new Error("Network Error: " + err.message);
  }
};

//###########################################################
export var getAsset = async function(url) {
  var err, response;
  try {
    response = (await fetch(url));
    if (!response.ok) {
      throw new Error("Response not ok - status: " + response.status + "!");
    }
    return URL.createObjectURL((await response.blob()));
  } catch (error) {
    err = error;
    throw new Error("Network Error: " + err.message);
  }
};

//###########################################################
export var getText = async function(url) {
  var err, response;
  try {
    response = (await fetch(url));
    if (!response.ok) {
      throw new Error("Response not ok - status: " + response.status + "!");
    }
    return (await response.text());
  } catch (error) {
    err = error;
    throw new Error("Network Error: " + err.message);
  }
};
